[package]
name = "jwt"
version = "0.4.0"
authors = ["Michael Yang <mikkyangg@gmail.com>"]
description = "JSON Web Token library"
documentation = "http://mikkyang.github.io/rust-jwt/doc/jwt/index.html"
homepage = "http://github.com/mikkyang/rust-jwt"
repository = "http://github.com/mikkyang/rust-jwt"
readme = "README.md"
keywords = ["JWT", "token", "web"]
license = "MIT"

[dependencies]
rust-crypto = "0.2"
rustc-serialize = "0.3"
